name=input("what is your name?")
city=input('what is your city?')
date=input("enter today's date in dd/mm/yyyy format")
favouriteThings=input("enter your favourite things?")
print("Personal deatils")
print("======================")
print("Name : "+name)
print("City : "+city)
print("Date : "+date)
print("Favourite things : "+favouriteThings)