from fastapi import status

SUCCESS = status.HTTP_200_OK
CREATED = status.HTTP_201_CREATED
BAD_REQUEST = status.HTTP_400_BAD_REQUEST
NOT_FOUND = status.HTTP_404_NOT_FOUND
UPDATED = status.HTTP_200_OK
DELETED = status.HTTP_200_OK
INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR