name = input("Enter your name: ")
city = input("Enter your city: ")
date = input("Enter today's date: ")
favorite_food = input("Enter your favorite food: ")
favorite_color = input("Enter your favorite color: ")
favorite_hobby = input("Enter your favorite hobby: ")
print("PERSONAL DETAILS")
print(f"Name             : {name}")
print(f"City             : {city}")
print(f"Today's Date     : {date}")
print(f"Favorite Food    : {favorite_food}")
print(f"Favorite Color   : {favorite_color}")
print(f"Favorite Hobby   : {favorite_hobby}")
